# Generated by Django 4.0.4 on 2022-05-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='URL Title'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='URL Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Inactive')),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
